name: Building Fluent Operator image

on:
  push:
    branches:
      - 'publish'

jobs:
  operator-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
      contents: read
    name: Build Image for Fluent Operator
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image for Fluent Operator
        run: |
          tag=$(cat VERSION | tr -d " \t\n\r")
          make build-op -e FO_IMG=ghcr.io/l1ghtman2k/fluent-operator:$tag